# Generated by Django 4.0.2 on 2022-09-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schlmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
