# Generated by Django 4.0.2 on 2022-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schlmanagementapp', '0003_remove_students_name_students_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passport',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
